### importar funciones

In [111]:
import numpy as np

### definimos variables

In [112]:
temp = np.loadtxt("Temperatura_Valparaiso.dat"); print(temp)

[16.6 15.5 14.2 14.1 18.  21.5 22.1 19.  15.9 13.9 13.6 12.7 17.7 19.3
 18.8 17.  16.8 15.9 14.8 15.2 16.7 19.2 19.2 18.  17.2 15.8 14.8 14.6
 18.1 18.6 19.6 18.  16.  15.  14.3 14.2 14.9 16.9 16.6 16.  15.8 14.8
 14.8 15.  16.4 17.2 16.7 16.2 15.9 16.2 16.3 16.  17.7 19.7 19.4 17.9
 16.6 15.4 14.4 14.9 18.6 20.6 20.4 18.8 16.8 15.6 14.7 14.2 17.5 21.4
 22.2 19.6 17.  14.9 14.8 14.2 19.8 20.2 21.2 22.  20.2 15.9 15.4 15.8
 17.7 19.2 18.6 17.  15.1 14.8 13.5 13.7 14.9 16.1 18.5 16.8]


### Cuerpo del programa

In [113]:
print(temp.shape)
dia1 = temp[0:8]; print(type(dia1))
dia2 = temp[8:16]
dia3 = temp[16:24]
dia4 = temp[24:32]
dia5 = temp[32:40]
dia6 = temp[40:48]
dia7 = temp[48:56]
dia8 = temp[56:64]
dia9 = temp[64:72]
dia10 = temp[72:80]
dia11 = temp[80:88]
dia12 = temp[88:96]

(96,)
<class 'numpy.ndarray'>


In [114]:
def media(arreglo,fila):
    m = arreglo[fila-1,]
    s = 0
    for i in range(len(m)):
        s += m[i]
    d = len(m)
    return(s/d)

def desviacion(arreglo,fila):					
	m = arreglo[fila-1,]
	s = 0
	for r in range(len(m)):             
		s += (m[r]-media(arreglo,fila))**2
	return(np.sqrt(s/(len(m)-1)))

In [115]:
matriz = np.asarray([dia1,dia2,dia3,dia4,dia5,dia6,dia7,dia8,dia9,dia10,dia11,dia12]); print(matriz)

[[16.6 15.5 14.2 14.1 18.  21.5 22.1 19. ]
 [15.9 13.9 13.6 12.7 17.7 19.3 18.8 17. ]
 [16.8 15.9 14.8 15.2 16.7 19.2 19.2 18. ]
 [17.2 15.8 14.8 14.6 18.1 18.6 19.6 18. ]
 [16.  15.  14.3 14.2 14.9 16.9 16.6 16. ]
 [15.8 14.8 14.8 15.  16.4 17.2 16.7 16.2]
 [15.9 16.2 16.3 16.  17.7 19.7 19.4 17.9]
 [16.6 15.4 14.4 14.9 18.6 20.6 20.4 18.8]
 [16.8 15.6 14.7 14.2 17.5 21.4 22.2 19.6]
 [17.  14.9 14.8 14.2 19.8 20.2 21.2 22. ]
 [20.2 15.9 15.4 15.8 17.7 19.2 18.6 17. ]
 [15.1 14.8 13.5 13.7 14.9 16.1 18.5 16.8]]


In [40]:
print(media(matriz,1))
media0=[]
desviacion0=[]
for i in range(1,13):
    media0.append(media(matriz,i))
    desviacion0.append(desviacion(matriz,i))
print(media0,desviacion0)

17.625
[17.625, 16.112499999999997, 16.975, 17.0875, 15.4875, 15.862500000000002, 17.387500000000003, 17.462500000000002, 17.75, 18.012500000000003, 17.475, 15.424999999999999] [3.0890359106269485, 2.4953886041485176, 1.6943182362573699, 1.8341502508947145, 1.0287822204640091, 0.9179752564359076, 1.5347754605432393, 2.4639906655667345, 3.0246605476600887, 3.153427840122102, 1.7539750771970994, 1.6585277464408865]


In [116]:
def media1(lista):
    return(sum(lista)/len(lista))

def desviacionestandar(lista):
    s = 0
    media = sum(lista)/len(lista)
    for i in lista:
        s += (i - media)**2
    d = len(lista)-1
    return(np.sqrt(s/d))

T = temp
m,d=[],[]
for e in range(0,12):
    m.append(media1(T[int(e*8):int(e*8+8)]))
    d.append(desviacionestandar(T[int(e*8):int(e*8+8)]))
print(m,d)

[17.625, 16.112499999999997, 16.975, 17.0875, 15.4875, 15.862500000000002, 17.387500000000003, 17.462500000000002, 17.75, 18.012500000000003, 17.475, 15.424999999999999] [3.0890359106269485, 2.4953886041485176, 1.6943182362573699, 1.8341502508947145, 1.0287822204640091, 0.9179752564359076, 1.5347754605432393, 2.4639906655667345, 3.0246605476600887, 3.153427840122102, 1.7539750771970994, 1.6585277464408865]


In [117]:
print(matriz)

[[16.6 15.5 14.2 14.1 18.  21.5 22.1 19. ]
 [15.9 13.9 13.6 12.7 17.7 19.3 18.8 17. ]
 [16.8 15.9 14.8 15.2 16.7 19.2 19.2 18. ]
 [17.2 15.8 14.8 14.6 18.1 18.6 19.6 18. ]
 [16.  15.  14.3 14.2 14.9 16.9 16.6 16. ]
 [15.8 14.8 14.8 15.  16.4 17.2 16.7 16.2]
 [15.9 16.2 16.3 16.  17.7 19.7 19.4 17.9]
 [16.6 15.4 14.4 14.9 18.6 20.6 20.4 18.8]
 [16.8 15.6 14.7 14.2 17.5 21.4 22.2 19.6]
 [17.  14.9 14.8 14.2 19.8 20.2 21.2 22. ]
 [20.2 15.9 15.4 15.8 17.7 19.2 18.6 17. ]
 [15.1 14.8 13.5 13.7 14.9 16.1 18.5 16.8]]


In [118]:
# Se considera como la mañana a contar de las 6, es decir, la segunda columna y termina a las 6 pm. en la sexta columna

dia = matriz[:,1:6]

mediadia=[]
desviaciondia=[]

for i in range(1,13):
    mediadia.append(media(dia,i))
    desviaciondia.append(desviacion(dia,i))

#print(mediadia,desviaciondia)

#
#print(matriz)
noche = np.delete(matriz,(1,2,3,4,5),axis=1); #print(noche)

medianoche=[]
desviacionnoche=[]
for i in range(1,13):
    medianoche.append(media(noche,i))
    desviacionnoche.append(desviacion(noche,i))

#print(medianoche,desviacionnoche)


In [119]:
# con dia se asume que se refiere al dia completo, entonces

print(max(media0)) #El dia 10 fue el más caluroso
print(min(desviacion0)) 
print(min(media0)) #El dia 12 fue el más frío en promedio

18.012500000000003
0.9179752564359076
15.424999999999999


In [120]:
print(matriz)

[[16.6 15.5 14.2 14.1 18.  21.5 22.1 19. ]
 [15.9 13.9 13.6 12.7 17.7 19.3 18.8 17. ]
 [16.8 15.9 14.8 15.2 16.7 19.2 19.2 18. ]
 [17.2 15.8 14.8 14.6 18.1 18.6 19.6 18. ]
 [16.  15.  14.3 14.2 14.9 16.9 16.6 16. ]
 [15.8 14.8 14.8 15.  16.4 17.2 16.7 16.2]
 [15.9 16.2 16.3 16.  17.7 19.7 19.4 17.9]
 [16.6 15.4 14.4 14.9 18.6 20.6 20.4 18.8]
 [16.8 15.6 14.7 14.2 17.5 21.4 22.2 19.6]
 [17.  14.9 14.8 14.2 19.8 20.2 21.2 22. ]
 [20.2 15.9 15.4 15.8 17.7 19.2 18.6 17. ]
 [15.1 14.8 13.5 13.7 14.9 16.1 18.5 16.8]]


In [123]:
for i in range(13,1):
    matriz=matriz[i:]
print(matriz)

#matriz = np.asarray([list(reversed([dia1,dia2,dia3,dia4,dia5,dia6,dia7,dia8,dia9,dia10,dia11,dia12]))]); print(matriz)

[[16.6 15.5 14.2 14.1 18.  21.5 22.1 19. ]
 [15.9 13.9 13.6 12.7 17.7 19.3 18.8 17. ]
 [16.8 15.9 14.8 15.2 16.7 19.2 19.2 18. ]
 [17.2 15.8 14.8 14.6 18.1 18.6 19.6 18. ]
 [16.  15.  14.3 14.2 14.9 16.9 16.6 16. ]
 [15.8 14.8 14.8 15.  16.4 17.2 16.7 16.2]
 [15.9 16.2 16.3 16.  17.7 19.7 19.4 17.9]
 [16.6 15.4 14.4 14.9 18.6 20.6 20.4 18.8]
 [16.8 15.6 14.7 14.2 17.5 21.4 22.2 19.6]
 [17.  14.9 14.8 14.2 19.8 20.2 21.2 22. ]
 [20.2 15.9 15.4 15.8 17.7 19.2 18.6 17. ]
 [15.1 14.8 13.5 13.7 14.9 16.1 18.5 16.8]]


In [121]:
print(temp)
print(matriz.tolist())
listadelistas=matriz.tolist()

[16.6 15.5 14.2 14.1 18.  21.5 22.1 19.  15.9 13.9 13.6 12.7 17.7 19.3
 18.8 17.  16.8 15.9 14.8 15.2 16.7 19.2 19.2 18.  17.2 15.8 14.8 14.6
 18.1 18.6 19.6 18.  16.  15.  14.3 14.2 14.9 16.9 16.6 16.  15.8 14.8
 14.8 15.  16.4 17.2 16.7 16.2 15.9 16.2 16.3 16.  17.7 19.7 19.4 17.9
 16.6 15.4 14.4 14.9 18.6 20.6 20.4 18.8 16.8 15.6 14.7 14.2 17.5 21.4
 22.2 19.6 17.  14.9 14.8 14.2 19.8 20.2 21.2 22.  20.2 15.9 15.4 15.8
 17.7 19.2 18.6 17.  15.1 14.8 13.5 13.7 14.9 16.1 18.5 16.8]
[[16.6, 15.5, 14.2, 14.1, 18.0, 21.5, 22.1, 19.0], [15.9, 13.9, 13.6, 12.7, 17.7, 19.3, 18.8, 17.0], [16.8, 15.9, 14.8, 15.2, 16.7, 19.2, 19.2, 18.0], [17.2, 15.8, 14.8, 14.6, 18.1, 18.6, 19.6, 18.0], [16.0, 15.0, 14.3, 14.2, 14.9, 16.9, 16.6, 16.0], [15.8, 14.8, 14.8, 15.0, 16.4, 17.2, 16.7, 16.2], [15.9, 16.2, 16.3, 16.0, 17.7, 19.7, 19.4, 17.9], [16.6, 15.4, 14.4, 14.9, 18.6, 20.6, 20.4, 18.8], [16.8, 15.6, 14.7, 14.2, 17.5, 21.4, 22.2, 19.6], [17.0, 14.9, 14.8, 14.2, 19.8, 20.2, 21.2, 22.0], [20.2, 15.9